version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    executor:
      name: go/default
      tag: '1.18'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run: go test -p 2 ./...
      - go/save-cache

workflows:
  main:
    jobs:
      - test
